### ISSUE TITLE
vidsrc.cc episodes

### ISSUE THREAD

**Issue by Tommy0412** [giammirove/videogatherer#8] opened 2024-09-03 12:37 UTC
not retrieving m3u8 for episodes.
api_url must have season episode and type set 
like this 
const api_url = `https://${HOST}/api/episodes/${new_data_id}/servers?id=${id}&season=1&episode=1&type=tv&isMobile=false&v=${encodeURIComponent(v_value)}&vrf=${encodeURIComponent(enc(id))}`;

**Comment by giammirove** [comment] 2024-09-03 17:09
Hi,
thank you for the help.
The issue is fixed in https://github.com/giammirove/videogatherer/commit/82c872350bfef9cf117f37a1f7ad2c64b436904a.

**Closed by giammirove** 2024-09-03 17:09 UTC
